version: "3.1"

services:
  db:
    image: postgres:10
    env_file:
      - .env.prod

  redis:
    image: redis:6.2-alpine

  backend:
    image: theodofr/falco:latest
    command: gunicorn --bind 0.0.0.0:8000 --chdir /code --workers 2 --access-logfile - --error-logfile - -c root/gunicorn.py root.wsgi:application
    ports:
      - "80:8000"
    env_file:
      - .env.prod

  celery:
    image: theodofr/falco:latest
    command: celery worker -A root.celery -B -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler -c 4
    env_file:
      - .env.prod
