# Generated by Django 2.1.5 on 2019-02-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='projects.Project'),
        ),
    ]
