# Generated by Django 2.1.7 on 2019-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0003_auto_20190206_1338")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="wpt_api_key",
            field=models.CharField(default="WEBPAGETEST_API_KEY", max_length=100),
            preserve_default=False,
        )
    ]
