# Generated by Django 2.1.7 on 2019-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0005_projectauditparameters")]

    operations = [
        migrations.AlterField(
            model_name="projectauditparameters",
            name="network_shape",
            field=models.CharField(
                choices=[
                    ("CABLE", "Cable"),
                    ("DSL", "DSL"),
                    ("THREE_G_SLOW", "3GSlow"),
                    ("THREE_G", "3G"),
                    ("THREE_G_FAST", "3GFast"),
                    ("FOUR_G", "4G"),
                    ("LTE", "LTE"),
                    ("EDGE", "Edge"),
                    ("TWO_G", "2G"),
                    ("DIAL", "Dial"),
                    ("FIOS", "FIOS"),
                    ("NATIVE", "Native"),
                    ("CUSTOM", "custom"),
                ],
                max_length=20,
            ),
        )
    ]
