# Generated by Django 2.1.7 on 2019-04-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='members',
        ),
    ]
