# Generated by Django 2.2 on 2019-04-23 13:08

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [("projects", "0011_auto_20190416_1924")]

    operations = [
        migrations.AddField(
            model_name="script",
            name="script_encrypted",
            field=fernet_fields.fields.EncryptedTextField(default=""),
            preserve_default=False,
        )
    ]
