# Generated by Django 2.2 on 2019-04-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_custom_duplicate_script_script_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='script',
        ),
    ]
