# Generated by Django 2.2 on 2019-04-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0014_remove_script_script")]

    operations = [
        migrations.RenameField(
            model_name="script", old_name="script_encrypted", new_name="script"
        )
    ]
