# Generated by Django 2.2 on 2019-04-24 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("projects", "0015_auto_20190423_1536")]

    operations = [
        migrations.CreateModel(
            name="RollbackTest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rollback", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("-created_at",),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        )
    ]
