# Generated by Django 2.2 on 2019-04-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rollbacktest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RollbackTest',
        ),
    ]
