# Generated by Django 2.2 on 2019-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_delete_rollbacktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauditparameters',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
