# Generated by Django 2.2 on 2019-06-18 09:58

from django.db import migrations, models
import django.db.models.deletion


def generate_configuration_from_browser_and_location(apps, schema_editor):
    ProjectAuditParameters = apps.get_model("projects", "ProjectAuditParameters")
    AvailableAuditParameters = apps.get_model("projects", "AvailableAuditParameters")
    for row in ProjectAuditParameters.objects.all():
        configuration, _ = AvailableAuditParameters.objects.get_or_create(
            browser=row.browser,
            location=row.location,
            defaults={
                "location_label": row.location,
                "location_group": "Unknown",
            },
        )
        row.configuration = configuration
        row.save()


def generate_browser_and_location_from_configuration(apps, schema_editor):
    ProjectAuditParameters = apps.get_model("projects", "ProjectAuditParameters")
    for row in ProjectAuditParameters.objects.all():
        row.browser = row.configuration.browser
        row.location = row.configuration.location
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_availableauditparameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectauditparameters",
            name="configuration",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="projects.AvailableAuditParameters"),
        ),
        migrations.RunPython(generate_configuration_from_browser_and_location, reverse_code=generate_browser_and_location_from_configuration),
        migrations.AlterField(
            model_name="projectauditparameters",
            name="configuration",
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to="projects.AvailableAuditParameters"),
        ),
    ]
