# Generated by Django 2.2 on 2019-06-18 13:19

from django.db import migrations, models


def set_default_value(apps, schema_editor):
    ProjectAuditParameters = apps.get_model("projects", "ProjectAuditParameters")
    for row in ProjectAuditParameters.objects.all():
        row.browser = "Unknown"
        row.location = "Unknown"
        row.save()


class Migration(migrations.Migration):

    dependencies = [("projects", "0020_projectauditparameters_configuration")]

    operations = [
        migrations.AlterField(
            model_name="projectauditparameters",
            name="browser",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="projectauditparameters",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=set_default_value),
        migrations.RemoveField(model_name="projectauditparameters", name="browser"),
        migrations.RemoveField(model_name="projectauditparameters", name="location"),
    ]
