# Generated by Django 2.2 on 2019-06-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20190621_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
    ]
