# Generated by Django 2.2 on 2019-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0024_auto_20190628_1130")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True),
        )
    ]
