# Generated by Django 2.2 on 2019-08-28 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0025_project_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMemberRole",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("project", "user")}},
        ),
        migrations.AddField(
            model_name="project",
            name="members_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_new_of",
                through="projects.ProjectMemberRole",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
