# Generated by Django 2.2 on 2019-09-04 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0029_auto_20190904_1127"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="members_new"),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_of",
                through="projects.ProjectMemberRole",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
