# Generated by Django 2.2.4 on 2019-11-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0030_auto_20190904_1152")]

    operations = [
        migrations.AddField(
            model_name="availableauditparameters",
            name="wpt_instance_url",
            field=models.CharField(default="https://webpagetest.org", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="wpt_instance_url",
            field=models.CharField(default="https://webpagetest.org", max_length=100),
        ),
    ]
