# Generated by Django 3.0.7 on 2020-09-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20200910_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginscript',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
