# Generated by Django 2.2 on 2019-06-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsnew',
            name='last_update_newsletter',
            field=models.DateTimeField(),
        ),
    ]
