# Generated by Django 2.1.7 on 2019-04-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_auto_20190410_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditresults',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.Audit'),
        ),
    ]
