# Generated by Django 2.2 on 2019-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("audits", "0011_auto_20190624_1622")]

    operations = [
        migrations.AddField(
            model_name="auditresults",
            name="wpt_metric_first_view_visually_complete",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditresults",
            name="wpt_metric_repeat_view_visually_complete",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
