# Generated by Django 2.2 on 2019-08-07 09:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("audits", "0012_auto_20190724_1157")]

    operations = [
        migrations.AddField(
            model_name="auditstatushistory",
            name="info",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="auditstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("QUEUEING", "QUEUEING"),
                    ("RUNNING", "RUNNING"),
                    ("PENDING", "PENDING"),
                    ("ERROR", "ERROR"),
                    ("SUCCESS", "SUCCESS"),
                ],
                max_length=10,
            ),
        ),
    ]
