# Generated by Django 2.2 on 2019-08-21 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20190507_1239")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_visited_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
